apiVersion: ai.sap.com/v1alpha1
kind: Training
metadata:
  name: st22-shortdump-training
spec:
  template: st22-shortdump-training-template

  parameters:
    prompt_template: |
      You are an experienced SAP ABAP engineer and debugger.

      Analyze the following ST22 short dump JSON. Return ONLY JSON with:
      - root_cause
      - technical_analysis
      - suggested_fix_code
      - impact_analysis
      - priority
      - confidence

      Dump JSON:
      {{dump}}

    llm_provider: "openai"
    openai_model: "gpt-4o-mini"
    max_tokens: 800
    temperature: 0.0

    storage_db: "data/st22.db"

