apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: st22-shortdump-serving-template
spec:
  # Name in registry
  image: "docker.io/s0026942030/shortdump:latest"

  # Container port exposed via FastAPI
  ports:
    - name: http
      port: 8080

  # Optional: registry auth
  imagePullSecrets:
    - name: rajdoc-registry

  # ENV variables passed during serving creation OR via runtime
  env:
    - name: LOG_LEVEL
      value: "INFO"

    # For OpenAI provider:
    - name: LLM_PROVIDER
      value: "openai"
    - name: OPENAI_MODEL
      value: "gpt-4o-mini"

    # If using local server:
    # - name: LLM_PROVIDER
    #   value: "local"
    # - name: LOCAL_LLM_URL
    #   value: "http://host.docker.internal:11434/api/generate"

    - name: STORAGE_DB
      value: "/app/data/st22.db"

  # Resources (optional)
  resources:
    limits:
      cpu: "1"
      memory: "1Gi"
