apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: st22-shortdump-serving-template
  annotations:
    scenarios.ai.sap.com/name: "Short dump use case"
    scenarios.ai.sap.com/description: "Short dump analysis"
    executables.ai.sap.com/name: "shortdump-executable"
    executables.ai.sap.com/description: "Short dump use case analysis"
  labels:
    ai.sap.com/version: "4.0"
    scenarios.ai.sap.com/id: "st22Shortdump"

spec:
  inputs:
    parameters:
      - name: dump_header
        type: string
      - name: dump_code
        type: string

  template:
    # 🚨 IMPORTANT:
    # "apiVersion/kind/spec" MUST BE A STRING BLOCK (|)
    apiVersion: serving.kserve.io/v1beta1
    kind: InferenceService

    spec: |
      predictor:
        minReplicas: 0
        maxReplicas: 1

        imagePullSecrets:
          - name: rajdoc-registry

        annotations:
          autoscaling.knative.dev/metric: "rps"
          autoscaling.knative.dev/target: "100"
          autoscaling.knative.dev/targetBurstCapacity: "70"
          serving.kserve.io/rest: "true"

        containers:
          - name: kserve-container
            image: docker.io/s0026942030/st22-gateway:latest

            ports:
              - name: http
                containerPort: 8080
                protocol: TCP

            env:
              # ---- AI Core environment ----
              - name: LLM_PROVIDER
                value: "sap_aicore"

              - name: AICORE_URL
                value: "https://api.ai.sap.com"

              - name: AICORE_DEPLOYMENT_ID
                value: "your-aicore-deployment-id"

              - name: AICORE_TOKEN_URL
                valueFrom:
                  secretKeyRef:
                    name: xsuaa-secret
                    key: url

              - name: AICORE_CLIENT_ID
                valueFrom:
                  secretKeyRef:
                    name: xsuaa-secret
                    key: clientid

              - name: AICORE_CLIENT_SECRET
                valueFrom:
                  secretKeyRef:
                    name: xsuaa-secret
                    key: clientsecret

              # Application settings
              - name: LOG_LEVEL
                value: "INFO"

              - name: STORAGE_DB
                value: "/app/data/st22.db"

            args:
              - "--handler=rest"
              - "--rest_path=/api/dumps"
              - >-
                --rest_body={
                  "dump_header": "{{inputs.parameters.dump_header}}",
                  "dump_code": "{{inputs.parameters.dump_code}}"
                }

            resources:
              limits:
                cpu: "1"
                memory: "1Gi"
