apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: st22-shortdump-serving-template-v3
spec:
  inputs:
    parameters:
      - name: dump_header
        type: string
      - name: dump_code
        type: string

  template:
    apiVersion: serving.kserve.io/v1beta1

    metadata:
      annotations: |
        serving.kserve.io/rest: "true"
      labels: |
        ai.sap.com/resourcePlan: basic

    spec: |
      predictor:
        containers:
          - name: kserve-container
            image: docker.io/s0026942030/st22-gateway:latest
            ports:
              - containerPort: 8080
            args:
              - "--handler=rest"
              - "--rest_path=/api/dumps"
              - >-
                --rest_body={
                  "dump_header":"{{inputs.parameters.dump_header}}",
                  "dump_code":"{{inputs.parameters.dump_code}}"
                }
