apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: st22-shortdump-serving-template
  annotations:
    scenarios.ai.sap.com/name: "Short dump use case"
    scenarios.ai.sap.com/description: "Short dump analysis"
    executables.ai.sap.com/name: "shortdump-executable"
    executables.ai.sap.com/description: "Short dump use case analysis"
  labels:
    ai.sap.com/version: "4.0"
    scenarios.ai.sap.com/id: "st22Shortdump"

spec:
  inputs:
    parameters:
      - name: dump_header         # NEW
        type: string
      - name: dump_code           # NEW
        type: string

  template:
    apiVersion: serving.kserve.io/v1beta1
    kind: InferenceService

    metadata:
      annotations: |
        autoscaling.knative.dev/metric: rps
        autoscaling.knative.dev/target: "100"
        autoscaling.knative.dev/targetBurstCapacity: "70"
        serving.kserve.io/rest: "true"   # IMPORTANT

    spec: |
      predictor:
        minReplicas: 0
        maxReplicas: 1
        imagePullSecrets:
          - name: rajdoc-registry
        containers:
          - name: kserve-container
            image: docker.io/s0026942030/shortdump:latest
            ports:
              - name: http
                containerPort: 8080
                protocol: TCP

            # IMPORTANT: Tell KServe how to POST to your FastAPI endpoint
            args:
              - "--model_name={{inputs.parameters.dump_header}}"
              - "--model_payload={
                  \"dump_header\": {{inputs.parameters.dump_header}},
                  \"dump_code\": {{inputs.parameters.dump_code}}
                }"
              - "--model_uri=http://127.0.0.1:8080/api/dumps"

            env:
              - name: LOG_LEVEL
                value: "INFO"
              - name: LLM_PROVIDER
                value: "openai"
              - name: OPENAI_MODEL
                value: "gpt-4o-mini"
              - name: STORAGE_DB
                value: "/app/data/st22.db"

            resources:
              limits:
                cpu: "1"
                memory: "1Gi"
