apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: st22-shortdump-serving-template
spec:
  template:
    spec: |
      apiVersion: serving.kserve.io/v1beta1
      kind: InferenceService
      metadata:
        name: st22-shortdump-isvc
      spec:
        predictor:
          containers:
            - name: shortdump
              image: docker.io/s0026942030/shortdump:latest
              ports:
                - name: http
                  containerPort: 8080
              env:
                - name: LOG_LEVEL
                  value: "INFO"
        imagePullSecrets:
          - name: rajdoc-registry
