apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: st22-shortdump-serving-template
spec:
  image: docker.io/s0026942030/shortdump:latest
  imagePullSecrets:
    - name: rajdoc-registry
  ports:
    - name: http
      containerPort: 8080

  command: ["python"]
  args: ["-m", "app.main"]

  env:
    - name: LOG_LEVEL
      value: "INFO"
    - name: LLM_PROVIDER
      value: "openai"
    - name: OPENAI_MODEL
      value: "gpt-4o-mini"
    - name: STORAGE_DB
      value: "/app/data/st22.db"

  resources:
    limits:
      cpu: "1"
      memory: "1Gi"
