apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: st22-shortdump-serving-template
spec:
  template:
    containers:
      - name: shortdump
        image: docker.io/s0026942030/shortdump:latest
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        env:
          - name: LOG_LEVEL
            value: "INFO"
    imagePullSecrets:
      - name: rajdoc-registry
