apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: st22-shortdump-serving-template  
  annotations:
    scenarios.ai.sap.com/name: "Short dump use case"
    scenarios.ai.sap.com/description: "Short dump analysis"
    executables.ai.sap.com/name: "Short-dump-Executable"
    executables.ai.sap.com/description: "Short dump use case analysis"
  labels:
    ai.sap.com/version: "4.0"
    scenarios.ai.sap.com/id: "st22Shortdump"

spec:
  template:
    spec:
      containers:
        - name: shortdump
          image: docker.io/s0026942030/simple-test:latest
          ports:
            - containerPort: 8080
          env:
            - name: LOG_LEVEL
              value: "INFO"
            - name: LLM_PROVIDER
              value: "openai"
            - name: OPENAI_MODEL
              value: "gpt-4o-mini"
            - name: STORAGE_DB
              value: "/app/data/st22.db"
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"

      imagePullSecrets:
        - name: rajdoc-registry

      replicaCount: 1
